/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ComponentEvent;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Andreas Aldito
 */
public class ADMIN extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN
     */
    public ADMIN() {
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        jLabel1.setSize(Toolkit.getDefaultToolkit().getScreenSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuBarangxSupplier = new javax.swing.JMenuItem();
        MenuKaryawan = new javax.swing.JMenuItem();
        MenuKategori = new javax.swing.JMenuItem();
        MenuMember = new javax.swing.JMenuItem();
        MenuRole = new javax.swing.JMenuItem();
        MenuShift = new javax.swing.JMenuItem();
        MenuUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/background adminXXX.png"))); // NOI18N

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Log Out");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        MenuBarangxSupplier.setText("Data Barang & Supplier");
        MenuBarangxSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarangxSupplierActionPerformed(evt);
            }
        });
        jMenu2.add(MenuBarangxSupplier);

        MenuKaryawan.setText("Data Karyawan");
        MenuKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKaryawanActionPerformed(evt);
            }
        });
        jMenu2.add(MenuKaryawan);

        MenuKategori.setText("Kategori Barang");
        MenuKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKategoriActionPerformed(evt);
            }
        });
        jMenu2.add(MenuKategori);

        MenuMember.setText("Member");
        MenuMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMemberActionPerformed(evt);
            }
        });
        jMenu2.add(MenuMember);

        MenuRole.setText("Role");
        MenuRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRoleActionPerformed(evt);
            }
        });
        jMenu2.add(MenuRole);

        MenuShift.setText("Shift");
        MenuShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuShiftActionPerformed(evt);
            }
        });
        jMenu2.add(MenuShift);

        MenuUser.setText("User");
        MenuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUserActionPerformed(evt);
            }
        });
        jMenu2.add(MenuUser);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void componentResized(ComponentEvent e) 
    {
        ADMIN adm = new ADMIN();
        if (e.getSource() == adm) 
        {

            //jInternalShift.setBounds(0, 0, adm.getContentPane().getWidth() / 4, adm.getContentPane().getHeight());
            //jInternalShift.setBounds(adm.getContentPane().getWidth() / 4, 0, adm.getContentPane().getWidth() / 2, adm.getContentPane().getHeight() / 2);

            // and so on
            // also can use yourDesktopPane instead of yourFrame.getContentPane()

        }
}
    
    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void MenuShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuShiftActionPerformed
        // TODO add your handling code here:
        FormShift fShift = new FormShift();
        fShift.setVisible(true);
    }//GEN-LAST:event_MenuShiftActionPerformed

    private void MenuMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMemberActionPerformed
        // TODO add your handling code here:
        FormMember fMember = new FormMember();
        fMember.setVisible(true);
    }//GEN-LAST:event_MenuMemberActionPerformed

    private void MenuBarangxSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarangxSupplierActionPerformed
        // TODO add your handling code here:
        FormBarangXSupplier fBarangxSuppplier = new FormBarangXSupplier();
        fBarangxSuppplier.setVisible(true);
    }//GEN-LAST:event_MenuBarangxSupplierActionPerformed

    private void MenuKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKategoriActionPerformed
        // TODO add your handling code here:
        FormKategoriBarang fKat = new FormKategoriBarang();
        fKat.setVisible(true);
    }//GEN-LAST:event_MenuKategoriActionPerformed

    private void MenuKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKaryawanActionPerformed
        // TODO add your handling code here:
        FormPegawaixManager fPegMan = new FormPegawaixManager();
        fPegMan.setVisible(true);
    }//GEN-LAST:event_MenuKaryawanActionPerformed

    private void MenuRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRoleActionPerformed
        // TODO add your handling code here:
        FormRole fRole = new FormRole();
        fRole.setVisible(true);
    }//GEN-LAST:event_MenuRoleActionPerformed

    private void MenuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUserActionPerformed
        // TODO add your handling code here:
        FormUser fUser = new FormUser();
        fUser.setVisible(true);
    }//GEN-LAST:event_MenuUserActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        FormLogin fl = new FormLogin();
        fl.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuBarangxSupplier;
    private javax.swing.JMenuItem MenuKaryawan;
    private javax.swing.JMenuItem MenuKategori;
    private javax.swing.JMenuItem MenuMember;
    private javax.swing.JMenuItem MenuRole;
    private javax.swing.JMenuItem MenuShift;
    private javax.swing.JMenuItem MenuUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
