/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.SwingConstants;
import javax.swing.JOptionPane; 

/**
 *
 * @author Andreas Aldito
 */
public class FormPegawaixManager extends javax.swing.JFrame implements SwingConstants
{

    /**
     * Creates new form Transaksi
     */
    public FormPegawaixManager() {
        initComponents();
        //this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        this.jLabel68.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        //this.jLabel13.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        this.setVisible(true);
        this.setResizable(false);
        //this.setAlwaysOnTop(true);
        this.jPanel3.setOpaque(false);;
        this.jPaneRegisterPeg.setVisible(false);
        this.jPaneEditPeg.setVisible(false);
        this.jPaneEditMgr.setVisible(false);
        this.jPaneRegisterMgr.setVisible(false);
        //this.jButton9.setHorizontalTextPosition( SwingConstants.RIGHT );
        //this.jButton9.setHorizontalAlignment(SwingConstants.RIGHT);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPaneEditMgr = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jComboBox9 = new javax.swing.JComboBox();
        jLabel56 = new javax.swing.JLabel();
        jPaneEdit3 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jComboBox10 = new javax.swing.JComboBox();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jComboBox11 = new javax.swing.JComboBox();
        jLabel67 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jComboBox32 = new javax.swing.JComboBox();
        jComboBox33 = new javax.swing.JComboBox();
        jComboBox34 = new javax.swing.JComboBox();
        jComboBox35 = new javax.swing.JComboBox();
        jComboBox36 = new javax.swing.JComboBox();
        jComboBox37 = new javax.swing.JComboBox();
        jPaneRegisterMgr = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jComboBox50 = new javax.swing.JComboBox();
        jComboBox51 = new javax.swing.JComboBox();
        jComboBox52 = new javax.swing.JComboBox();
        jComboBox53 = new javax.swing.JComboBox();
        jComboBox54 = new javax.swing.JComboBox();
        jComboBox55 = new javax.swing.JComboBox();
        jPaneEditPeg = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jPaneEdit1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel45 = new javax.swing.JLabel();
        jComboBox38 = new javax.swing.JComboBox();
        jComboBox39 = new javax.swing.JComboBox();
        jComboBox40 = new javax.swing.JComboBox();
        jComboBox41 = new javax.swing.JComboBox();
        jComboBox42 = new javax.swing.JComboBox();
        jComboBox43 = new javax.swing.JComboBox();
        jPaneRegisterPeg = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jComboBox44 = new javax.swing.JComboBox();
        jComboBox45 = new javax.swing.JComboBox();
        jComboBox46 = new javax.swing.JComboBox();
        jComboBox47 = new javax.swing.JComboBox();
        jComboBox48 = new javax.swing.JComboBox();
        jComboBox49 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel68 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPaneEditMgr.setBackground(new java.awt.Color(250, 205, 138));
        jPaneEditMgr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPaneEditMgr.setLayout(null);

        jLabel46.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel46.setText("Edit Manager");
        jPaneEditMgr.add(jLabel46);
        jLabel46.setBounds(210, 20, 150, 35);

        jLabel47.setText("Posisi");
        jPaneEditMgr.add(jLabel47);
        jLabel47.setBounds(20, 120, 160, 14);

        jButton15.setText("Simpan");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPaneEditMgr.add(jButton15);
        jButton15.setBounds(420, 400, 72, 23);

        jButton16.setText("Batal");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPaneEditMgr.add(jButton16);
        jButton16.setBounds(500, 400, 63, 23);

        jLabel48.setText("Nama");
        jPaneEditMgr.add(jLabel48);
        jLabel48.setBounds(20, 60, 190, 14);
        jPaneEditMgr.add(jTextField23);
        jTextField23.setBounds(20, 80, 260, 30);

        jLabel49.setText("Username");
        jPaneEditMgr.add(jLabel49);
        jLabel49.setBounds(20, 180, 150, 14);
        jPaneEditMgr.add(jTextField24);
        jTextField24.setBounds(20, 200, 260, 30);

        jLabel50.setText("Tgl. Lahir");
        jPaneEditMgr.add(jLabel50);
        jLabel50.setBounds(20, 240, 110, 14);

        jLabel51.setText("Jenis Kelamin");
        jPaneEditMgr.add(jLabel51);
        jLabel51.setBounds(20, 300, 150, 14);

        jRadioButton9.setText("Laki-laki");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        jPaneEditMgr.add(jRadioButton9);
        jRadioButton9.setBounds(20, 320, 100, 30);

        jRadioButton10.setText("Perempuan");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        jPaneEditMgr.add(jRadioButton10);
        jRadioButton10.setBounds(130, 320, 150, 30);

        jLabel52.setText("Mulai Bekerja");
        jPaneEditMgr.add(jLabel52);
        jLabel52.setBounds(310, 60, 210, 14);

        jLabel53.setText("Gaji");
        jPaneEditMgr.add(jLabel53);
        jLabel53.setBounds(310, 120, 160, 14);
        jPaneEditMgr.add(jTextField25);
        jTextField25.setBounds(310, 140, 260, 30);
        jPaneEditMgr.add(jTextField26);
        jTextField26.setBounds(310, 320, 260, 30);

        jLabel54.setText("Alamat");
        jPaneEditMgr.add(jLabel54);
        jLabel54.setBounds(310, 180, 200, 14);

        jLabel55.setText("No. Telp");
        jPaneEditMgr.add(jLabel55);
        jLabel55.setBounds(310, 240, 180, 14);
        jPaneEditMgr.add(jTextField27);
        jTextField27.setBounds(310, 200, 260, 30);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPaneEditMgr.add(jComboBox9);
        jComboBox9.setBounds(20, 140, 260, 30);

        jLabel56.setText("Shift");
        jPaneEditMgr.add(jLabel56);
        jLabel56.setBounds(310, 300, 190, 14);

        jPaneEdit3.setBackground(new java.awt.Color(250, 205, 138));
        jPaneEdit3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPaneEdit3.setLayout(null);

        jLabel57.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel57.setText("Edit Pegawai");
        jPaneEdit3.add(jLabel57);
        jLabel57.setBounds(220, 20, 140, 35);

        jLabel58.setText("Posisi");
        jPaneEdit3.add(jLabel58);
        jLabel58.setBounds(20, 120, 160, 14);

        jButton17.setText("Simpan");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPaneEdit3.add(jButton17);
        jButton17.setBounds(420, 400, 72, 23);

        jButton18.setText("Batal");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPaneEdit3.add(jButton18);
        jButton18.setBounds(500, 400, 63, 23);

        jLabel59.setText("Nama");
        jPaneEdit3.add(jLabel59);
        jLabel59.setBounds(20, 60, 190, 14);
        jPaneEdit3.add(jTextField28);
        jTextField28.setBounds(20, 80, 260, 30);

        jLabel60.setText("Username");
        jPaneEdit3.add(jLabel60);
        jLabel60.setBounds(20, 180, 150, 14);
        jPaneEdit3.add(jTextField29);
        jTextField29.setBounds(20, 200, 260, 30);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPaneEdit3.add(jComboBox10);
        jComboBox10.setBounds(310, 320, 260, 30);

        jLabel61.setText("Tgl. Lahir");
        jPaneEdit3.add(jLabel61);
        jLabel61.setBounds(20, 240, 110, 14);

        jLabel62.setText("Jenis Kelamin");
        jPaneEdit3.add(jLabel62);
        jLabel62.setBounds(20, 300, 150, 14);

        jRadioButton11.setText("Laki-laki");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        jPaneEdit3.add(jRadioButton11);
        jRadioButton11.setBounds(20, 320, 100, 30);

        jRadioButton12.setText("Perempuan");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        jPaneEdit3.add(jRadioButton12);
        jRadioButton12.setBounds(130, 320, 150, 30);

        jLabel63.setText("Mulai Bekerja");
        jPaneEdit3.add(jLabel63);
        jLabel63.setBounds(310, 60, 210, 14);

        jLabel64.setText("Gaji");
        jPaneEdit3.add(jLabel64);
        jLabel64.setBounds(310, 120, 160, 14);
        jPaneEdit3.add(jTextField30);
        jTextField30.setBounds(310, 140, 260, 30);
        jPaneEdit3.add(jTextField31);
        jTextField31.setBounds(310, 260, 260, 30);

        jLabel65.setText("Alamat");
        jPaneEdit3.add(jLabel65);
        jLabel65.setBounds(310, 180, 200, 14);

        jLabel66.setText("No. Telp");
        jPaneEdit3.add(jLabel66);
        jLabel66.setBounds(310, 240, 180, 14);
        jPaneEdit3.add(jTextField32);
        jTextField32.setBounds(310, 200, 260, 30);

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPaneEdit3.add(jComboBox11);
        jComboBox11.setBounds(20, 140, 260, 30);

        jLabel67.setText("Shift");
        jPaneEdit3.add(jLabel67);
        jLabel67.setBounds(310, 300, 190, 14);

        jPaneEditMgr.add(jPaneEdit3);
        jPaneEdit3.setBounds(760, 620, 580, 440);
        jPaneEditMgr.add(jTextField33);
        jTextField33.setBounds(310, 260, 260, 30);

        jComboBox32.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hari", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPaneEditMgr.add(jComboBox32);
        jComboBox32.setBounds(310, 80, 70, 30);

        jComboBox33.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bulan", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPaneEditMgr.add(jComboBox33);
        jComboBox33.setBounds(390, 80, 100, 30);

        jComboBox34.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tahun", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));
        jPaneEditMgr.add(jComboBox34);
        jComboBox34.setBounds(500, 80, 70, 30);

        jComboBox35.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hari", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPaneEditMgr.add(jComboBox35);
        jComboBox35.setBounds(20, 260, 70, 30);

        jComboBox36.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bulan", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPaneEditMgr.add(jComboBox36);
        jComboBox36.setBounds(100, 260, 100, 30);

        jComboBox37.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tahun", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));
        jPaneEditMgr.add(jComboBox37);
        jComboBox37.setBounds(210, 260, 70, 30);

        getContentPane().add(jPaneEditMgr);
        jPaneEditMgr.setBounds(860, 650, 580, 440);

        jPaneRegisterMgr.setBackground(new java.awt.Color(250, 205, 138));
        jPaneRegisterMgr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPaneRegisterMgr.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel15.setText("Tambah Manager");
        jPaneRegisterMgr.add(jLabel15);
        jLabel15.setBounds(180, 20, 200, 35);

        jLabel17.setText("Posisi");
        jPaneRegisterMgr.add(jLabel17);
        jLabel17.setBounds(20, 120, 160, 14);

        jButton6.setText("Simpan");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPaneRegisterMgr.add(jButton6);
        jButton6.setBounds(420, 400, 72, 23);

        jButton8.setText("Batal");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPaneRegisterMgr.add(jButton8);
        jButton8.setBounds(500, 400, 63, 23);

        jLabel27.setText("Nama");
        jPaneRegisterMgr.add(jLabel27);
        jLabel27.setBounds(20, 60, 190, 14);
        jPaneRegisterMgr.add(jTextField10);
        jTextField10.setBounds(20, 80, 260, 30);

        jLabel28.setText("Username");
        jPaneRegisterMgr.add(jLabel28);
        jLabel28.setBounds(20, 180, 150, 14);
        jPaneRegisterMgr.add(jTextField14);
        jTextField14.setBounds(20, 200, 260, 30);

        jLabel29.setText("Tgl. Lahir");
        jPaneRegisterMgr.add(jLabel29);
        jLabel29.setBounds(20, 240, 110, 14);

        jLabel30.setText("Jenis Kelamin");
        jPaneRegisterMgr.add(jLabel30);
        jLabel30.setBounds(20, 300, 150, 14);

        jRadioButton5.setText("Laki-laki");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPaneRegisterMgr.add(jRadioButton5);
        jRadioButton5.setBounds(20, 320, 100, 30);

        jRadioButton6.setText("Perempuan");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPaneRegisterMgr.add(jRadioButton6);
        jRadioButton6.setBounds(130, 320, 150, 30);

        jLabel31.setText("Mulai Bekerja");
        jPaneRegisterMgr.add(jLabel31);
        jLabel31.setBounds(310, 60, 210, 14);

        jLabel32.setText("Gaji");
        jPaneRegisterMgr.add(jLabel32);
        jLabel32.setBounds(310, 120, 160, 14);
        jPaneRegisterMgr.add(jTextField2);
        jTextField2.setBounds(310, 140, 260, 30);
        jPaneRegisterMgr.add(jTextField15);
        jTextField15.setBounds(310, 320, 260, 30);

        jLabel33.setText("Alamat");
        jPaneRegisterMgr.add(jLabel33);
        jLabel33.setBounds(310, 180, 200, 14);

        jLabel34.setText("No. Telp");
        jPaneRegisterMgr.add(jLabel34);
        jLabel34.setBounds(310, 240, 180, 14);
        jPaneRegisterMgr.add(jTextField16);
        jTextField16.setBounds(310, 200, 260, 30);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPaneRegisterMgr.add(jComboBox6);
        jComboBox6.setBounds(20, 140, 260, 30);

        jLabel35.setText("Bonus");
        jPaneRegisterMgr.add(jLabel35);
        jLabel35.setBounds(310, 300, 190, 14);
        jPaneRegisterMgr.add(jTextField17);
        jTextField17.setBounds(310, 260, 260, 30);

        jComboBox50.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hari", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPaneRegisterMgr.add(jComboBox50);
        jComboBox50.setBounds(310, 80, 70, 30);

        jComboBox51.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bulan", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPaneRegisterMgr.add(jComboBox51);
        jComboBox51.setBounds(390, 80, 100, 30);

        jComboBox52.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tahun", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));
        jPaneRegisterMgr.add(jComboBox52);
        jComboBox52.setBounds(500, 80, 70, 30);

        jComboBox53.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hari", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPaneRegisterMgr.add(jComboBox53);
        jComboBox53.setBounds(20, 260, 70, 30);

        jComboBox54.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bulan", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPaneRegisterMgr.add(jComboBox54);
        jComboBox54.setBounds(100, 260, 100, 30);

        jComboBox55.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tahun", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));
        jPaneRegisterMgr.add(jComboBox55);
        jComboBox55.setBounds(210, 260, 70, 30);

        getContentPane().add(jPaneRegisterMgr);
        jPaneRegisterMgr.setBounds(170, 660, 580, 440);

        jPaneEditPeg.setBackground(new java.awt.Color(250, 205, 138));
        jPaneEditPeg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPaneEditPeg.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel12.setText("Edit Pegawai");
        jPaneEditPeg.add(jLabel12);
        jLabel12.setBounds(220, 20, 140, 35);

        jLabel16.setText("Posisi");
        jPaneEditPeg.add(jLabel16);
        jLabel16.setBounds(20, 120, 160, 14);

        jButton3.setText("Simpan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPaneEditPeg.add(jButton3);
        jButton3.setBounds(420, 400, 72, 23);

        jButton4.setText("Batal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPaneEditPeg.add(jButton4);
        jButton4.setBounds(500, 400, 63, 23);

        jLabel18.setText("Nama");
        jPaneEditPeg.add(jLabel18);
        jLabel18.setBounds(20, 60, 190, 14);
        jPaneEditPeg.add(jTextField5);
        jTextField5.setBounds(20, 80, 260, 30);

        jLabel19.setText("Username");
        jPaneEditPeg.add(jLabel19);
        jLabel19.setBounds(20, 180, 150, 14);
        jPaneEditPeg.add(jTextField9);
        jTextField9.setBounds(20, 200, 260, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPaneEditPeg.add(jComboBox3);
        jComboBox3.setBounds(310, 320, 260, 30);

        jLabel20.setText("Tgl. Lahir");
        jPaneEditPeg.add(jLabel20);
        jLabel20.setBounds(20, 240, 110, 14);

        jLabel21.setText("Jenis Kelamin");
        jPaneEditPeg.add(jLabel21);
        jLabel21.setBounds(20, 300, 150, 14);

        jRadioButton3.setText("Laki-laki");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPaneEditPeg.add(jRadioButton3);
        jRadioButton3.setBounds(20, 320, 100, 30);

        jRadioButton4.setText("Perempuan");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPaneEditPeg.add(jRadioButton4);
        jRadioButton4.setBounds(130, 320, 150, 30);

        jLabel22.setText("Mulai Bekerja");
        jPaneEditPeg.add(jLabel22);
        jLabel22.setBounds(310, 60, 210, 14);

        jLabel23.setText("Gaji");
        jPaneEditPeg.add(jLabel23);
        jLabel23.setBounds(310, 120, 160, 14);
        jPaneEditPeg.add(jTextField11);
        jTextField11.setBounds(310, 140, 260, 30);
        jPaneEditPeg.add(jTextField12);
        jTextField12.setBounds(310, 260, 260, 30);

        jLabel24.setText("Alamat");
        jPaneEditPeg.add(jLabel24);
        jLabel24.setBounds(310, 180, 200, 14);

        jLabel25.setText("No. Telp");
        jPaneEditPeg.add(jLabel25);
        jLabel25.setBounds(310, 240, 180, 14);
        jPaneEditPeg.add(jTextField13);
        jTextField13.setBounds(310, 200, 260, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPaneEditPeg.add(jComboBox4);
        jComboBox4.setBounds(20, 140, 260, 30);

        jLabel26.setText("Shift");
        jPaneEditPeg.add(jLabel26);
        jLabel26.setBounds(310, 300, 190, 14);

        jPaneEdit1.setBackground(new java.awt.Color(250, 205, 138));
        jPaneEdit1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPaneEdit1.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel13.setText("Edit Pegawai");
        jPaneEdit1.add(jLabel13);
        jLabel13.setBounds(220, 20, 140, 35);

        jLabel36.setText("Posisi");
        jPaneEdit1.add(jLabel36);
        jLabel36.setBounds(20, 120, 160, 14);

        jButton13.setText("Simpan");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPaneEdit1.add(jButton13);
        jButton13.setBounds(420, 400, 72, 23);

        jButton14.setText("Batal");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPaneEdit1.add(jButton14);
        jButton14.setBounds(500, 400, 63, 23);

        jLabel37.setText("Nama");
        jPaneEdit1.add(jLabel37);
        jLabel37.setBounds(20, 60, 190, 14);
        jPaneEdit1.add(jTextField18);
        jTextField18.setBounds(20, 80, 260, 30);

        jLabel38.setText("Username");
        jPaneEdit1.add(jLabel38);
        jLabel38.setBounds(20, 180, 150, 14);
        jPaneEdit1.add(jTextField19);
        jTextField19.setBounds(20, 200, 260, 30);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPaneEdit1.add(jComboBox5);
        jComboBox5.setBounds(310, 320, 260, 30);

        jLabel39.setText("Tgl. Lahir");
        jPaneEdit1.add(jLabel39);
        jLabel39.setBounds(20, 240, 110, 14);

        jLabel40.setText("Jenis Kelamin");
        jPaneEdit1.add(jLabel40);
        jLabel40.setBounds(20, 300, 150, 14);

        jRadioButton7.setText("Laki-laki");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPaneEdit1.add(jRadioButton7);
        jRadioButton7.setBounds(20, 320, 100, 30);

        jRadioButton8.setText("Perempuan");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        jPaneEdit1.add(jRadioButton8);
        jRadioButton8.setBounds(130, 320, 150, 30);

        jLabel41.setText("Mulai Bekerja");
        jPaneEdit1.add(jLabel41);
        jLabel41.setBounds(310, 60, 210, 14);

        jLabel42.setText("Gaji");
        jPaneEdit1.add(jLabel42);
        jLabel42.setBounds(310, 120, 160, 14);
        jPaneEdit1.add(jTextField20);
        jTextField20.setBounds(310, 140, 260, 30);
        jPaneEdit1.add(jTextField21);
        jTextField21.setBounds(310, 260, 260, 30);

        jLabel43.setText("Alamat");
        jPaneEdit1.add(jLabel43);
        jLabel43.setBounds(310, 180, 200, 14);

        jLabel44.setText("No. Telp");
        jPaneEdit1.add(jLabel44);
        jLabel44.setBounds(310, 240, 180, 14);
        jPaneEdit1.add(jTextField22);
        jTextField22.setBounds(310, 200, 260, 30);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPaneEdit1.add(jComboBox7);
        jComboBox7.setBounds(20, 140, 260, 30);

        jLabel45.setText("Shift");
        jPaneEdit1.add(jLabel45);
        jLabel45.setBounds(310, 300, 190, 14);

        jPaneEditPeg.add(jPaneEdit1);
        jPaneEdit1.setBounds(760, 620, 580, 440);

        jComboBox38.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hari", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPaneEditPeg.add(jComboBox38);
        jComboBox38.setBounds(310, 80, 70, 30);

        jComboBox39.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bulan", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPaneEditPeg.add(jComboBox39);
        jComboBox39.setBounds(390, 80, 100, 30);

        jComboBox40.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tahun", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));
        jPaneEditPeg.add(jComboBox40);
        jComboBox40.setBounds(500, 80, 70, 30);

        jComboBox41.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hari", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPaneEditPeg.add(jComboBox41);
        jComboBox41.setBounds(20, 260, 70, 30);

        jComboBox42.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bulan", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPaneEditPeg.add(jComboBox42);
        jComboBox42.setBounds(100, 260, 100, 30);

        jComboBox43.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tahun", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));
        jPaneEditPeg.add(jComboBox43);
        jComboBox43.setBounds(210, 260, 70, 30);

        getContentPane().add(jPaneEditPeg);
        jPaneEditPeg.setBounds(860, 600, 580, 440);

        jPaneRegisterPeg.setBackground(new java.awt.Color(250, 205, 138));
        jPaneRegisterPeg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPaneRegisterPeg.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel8.setText("Tambah Pegawai");
        jPaneRegisterPeg.add(jLabel8);
        jLabel8.setBounds(190, 20, 180, 35);

        jLabel9.setText("Posisi");
        jPaneRegisterPeg.add(jLabel9);
        jLabel9.setBounds(20, 120, 160, 14);

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPaneRegisterPeg.add(jButton1);
        jButton1.setBounds(420, 400, 72, 23);

        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPaneRegisterPeg.add(jButton2);
        jButton2.setBounds(500, 400, 63, 23);

        jLabel14.setText("Nama");
        jPaneRegisterPeg.add(jLabel14);
        jLabel14.setBounds(20, 60, 190, 14);
        jPaneRegisterPeg.add(jTextField4);
        jTextField4.setBounds(20, 80, 260, 30);

        jLabel2.setText("Username");
        jPaneRegisterPeg.add(jLabel2);
        jLabel2.setBounds(20, 180, 150, 14);
        jPaneRegisterPeg.add(jTextField6);
        jTextField6.setBounds(20, 200, 260, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPaneRegisterPeg.add(jComboBox1);
        jComboBox1.setBounds(310, 320, 260, 30);

        jLabel3.setText("Tgl. Lahir");
        jPaneRegisterPeg.add(jLabel3);
        jLabel3.setBounds(20, 240, 110, 14);

        jLabel4.setText("Jenis Kelamin");
        jPaneRegisterPeg.add(jLabel4);
        jLabel4.setBounds(20, 300, 150, 14);

        jRadioButton1.setText("Laki-laki");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPaneRegisterPeg.add(jRadioButton1);
        jRadioButton1.setBounds(20, 320, 100, 30);

        jRadioButton2.setText("Perempuan");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPaneRegisterPeg.add(jRadioButton2);
        jRadioButton2.setBounds(130, 320, 150, 30);

        jLabel5.setText("Mulai Bekerja");
        jPaneRegisterPeg.add(jLabel5);
        jLabel5.setBounds(310, 60, 210, 14);

        jLabel6.setText("Gaji");
        jPaneRegisterPeg.add(jLabel6);
        jLabel6.setBounds(310, 120, 160, 14);
        jPaneRegisterPeg.add(jTextField1);
        jTextField1.setBounds(310, 140, 260, 30);
        jPaneRegisterPeg.add(jTextField7);
        jTextField7.setBounds(310, 260, 260, 30);

        jLabel7.setText("Alamat");
        jPaneRegisterPeg.add(jLabel7);
        jLabel7.setBounds(310, 180, 200, 14);

        jLabel10.setText("No. Telp");
        jPaneRegisterPeg.add(jLabel10);
        jLabel10.setBounds(310, 240, 180, 14);
        jPaneRegisterPeg.add(jTextField8);
        jTextField8.setBounds(310, 200, 260, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPaneRegisterPeg.add(jComboBox2);
        jComboBox2.setBounds(20, 140, 260, 30);

        jLabel11.setText("Shift");
        jPaneRegisterPeg.add(jLabel11);
        jLabel11.setBounds(310, 300, 190, 14);

        jComboBox44.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hari", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPaneRegisterPeg.add(jComboBox44);
        jComboBox44.setBounds(310, 80, 70, 30);

        jComboBox45.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bulan", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPaneRegisterPeg.add(jComboBox45);
        jComboBox45.setBounds(390, 80, 100, 30);

        jComboBox46.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tahun", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));
        jPaneRegisterPeg.add(jComboBox46);
        jComboBox46.setBounds(500, 80, 70, 30);

        jComboBox47.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hari", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPaneRegisterPeg.add(jComboBox47);
        jComboBox47.setBounds(20, 260, 70, 30);

        jComboBox48.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bulan", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPaneRegisterPeg.add(jComboBox48);
        jComboBox48.setBounds(100, 260, 100, 30);

        jComboBox49.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tahun", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));
        jPaneRegisterPeg.add(jComboBox49);
        jComboBox49.setBounds(210, 260, 70, 30);

        getContentPane().add(jPaneRegisterPeg);
        jPaneRegisterPeg.setBounds(170, 610, 580, 440);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/Search-icon.png"))); // NOI18N
        jButton12.setText("Cari");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(980, 150, 360, 50);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/delete_converted.png"))); // NOI18N
        jButton5.setText("Hapus");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1220, 540, 123, 52);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/Login-out-icon.png"))); // NOI18N
        jButton9.setText("Logout");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(20, 660, 100, 40);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/edit_converted.png"))); // NOI18N
        jButton10.setText("Edit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(1090, 540, 120, 52);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/Add-user-icon.png"))); // NOI18N
        jButton11.setText("Tambah");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(960, 540, 120, 52);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/Computer-Hardware-Shutdown-icon.png"))); // NOI18N
        jButton7.setText("Keluar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(20, 710, 100, 40);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Posisi", "Username", "Tgl Lahir", "Jenis Kelamin", "Mulai Bekerja", "Gaji", "Alamat", "No. Telp", "Shift"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jTabbedPane1.addTab("Data Pegawai", jScrollPane2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Posisi", "Username", "Tgl Lahir", "Jenis Kelamin", "Mulai Bekerja", "Gaji", "Alamat", "No. Telp", "Bonus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);

        jTabbedPane1.addTab("Data Manager", jScrollPane3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(310, 200, 1030, 330);

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/bckgrnd2.png"))); // NOI18N
        getContentPane().add(jLabel68);
        jLabel68.setBounds(0, 0, 1370, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jTabbedPane1.getSelectedIndex()==0)//DataPegawai
        {
            int selectedOption = JOptionPane.showConfirmDialog(null, 
                                  "Apakah Anda Yakin ingin menghapus entri pegawai tersebut?", 
                                  "Peringatan", 
                                  JOptionPane.YES_NO_OPTION); 
            if (selectedOption == JOptionPane.YES_OPTION) 
            {
                JOptionPane.showMessageDialog(null, "Data telah dihapus");
            }            
        }
        
        if(jTabbedPane1.getSelectedIndex()==1)//DataManager
        {
            int selectedOption = JOptionPane.showConfirmDialog(null, 
                                  "Apakah Anda Yakin ingin menghapus entri manager tersebut?", 
                                  "Peringatan", 
                                  JOptionPane.YES_NO_OPTION); 
            if (selectedOption == JOptionPane.YES_OPTION) 
            {
                JOptionPane.showMessageDialog(null, "Data telah dihapus");
            }       
        }
        
            
    }//GEN-LAST:event_jButton5ActionPerformed

    private void setdisabled()
    {
        this.jButton11.setEnabled(false);
        this.jButton10.setEnabled(false);
        this.jButton5.setEnabled(false);
        this.jTextField3.setEnabled(false);
        this.jButton9.setEnabled(false);
        this.jButton7.setEnabled(false);
        this.jButton12.setEnabled(false);
        this.jTable2.setEnabled(false);
        jTable2.getTableHeader().setEnabled(false);
    }
    
    private void enablein()
    {
        this.jButton11.setEnabled(true);
        this.jButton10.setEnabled(true);
        this.jButton5.setEnabled(true);
        this.jTextField3.setEnabled(true);
        this.jButton9.setEnabled(true);
        this.jButton7.setEnabled(true);
        this.jButton12.setEnabled(true);
        this.jTable2.setEnabled(true);
        jTable2.getTableHeader().setEnabled(true);
    }
    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null, 
                                  "Apakah Anda yakin ingin logout?", 
                                  "Peringatan", 
                                  JOptionPane.YES_NO_OPTION); 
            if (selectedOption == JOptionPane.YES_OPTION) 
            {
                this.dispose();;
            }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if(jTabbedPane1.getSelectedIndex()==0)//DataPegawai
            {
                setdisabled();
                Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
                int x = (int) ((dimension.getWidth() - jPaneEditPeg.getWidth()) / 2);
                int y = (int) ((dimension.getHeight() - jPaneEditPeg.getHeight()) / 2);
                jPaneEditPeg.setLocation(x, y);
                this.jPaneEditPeg.setVisible(true);
                //this.datePicker3.setOpaque(false);
                //this.datePicker4.setOpaque(false);
            }
        
            if(jTabbedPane1.getSelectedIndex()==1)//DataManager
            {
                setdisabled();
                Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
                int x = (int) ((dimension.getWidth() - jPaneEditMgr.getWidth()) / 2);
                int y = (int) ((dimension.getHeight() - jPaneEditMgr.getHeight()) / 2);
                jPaneEditMgr.setLocation(x, y);
                this.jPaneEditMgr.setVisible(true);
                //this.datePicker9.setOpaque(false);
                //this.datePicker10.setOpaque(false);
            }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
            
        
            if(jTabbedPane1.getSelectedIndex()==0)//DataPegawai
            {
                setdisabled();
                Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
                int x = (int) ((dimension.getWidth() - jPaneRegisterPeg.getWidth()) / 2);
                int y = (int) ((dimension.getHeight() - jPaneRegisterPeg.getHeight()) / 2);
                jPaneRegisterPeg.setLocation(x, y);
                this.jPaneRegisterPeg.setVisible(true);
                //this.datePicker2.setOpaque(false);
                //this.datePicker1.setOpaque(false);
            }
        
            if(jTabbedPane1.getSelectedIndex()==1)//DataManager
            {
                setdisabled();
                Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
                int x = (int) ((dimension.getWidth() - jPaneRegisterMgr.getWidth()) / 2);
                int y = (int) ((dimension.getHeight() - jPaneRegisterMgr.getHeight()) / 2);
                jPaneRegisterMgr.setLocation(x, y);
                this.jPaneRegisterMgr.setVisible(true);
                //this.datePicker5.setOpaque(false);
                //this.datePicker6.setOpaque(false);
            }
        
            
       
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            int selectedOption = JOptionPane.showConfirmDialog(null, 
                                  "Apakah Anda yakin ingin menambah pegawai?", 
                                  "Peringatan", 
                                  JOptionPane.YES_NO_OPTION); 
            if (selectedOption == JOptionPane.YES_OPTION) 
            {
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                this.jPaneRegisterPeg.setVisible(false);
                enablein();
            }
            
            else
            {
                
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            
                this.jPaneRegisterPeg.setVisible(false);
                enablein();
            
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null, 
                                  "Apakah Anda yakin ingin keluar?", 
                                  "Peringatan", 
                                  JOptionPane.YES_NO_OPTION); 
            if (selectedOption == JOptionPane.YES_OPTION) 
            {
                this.dispose();;
            }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            int selectedOption = JOptionPane.showConfirmDialog(null, 
                                  "Apakah Anda yakin ingin mengedit pegawai?", 
                                  "Peringatan", 
                                  JOptionPane.YES_NO_OPTION); 
            if (selectedOption == JOptionPane.YES_OPTION) 
            {
                JOptionPane.showMessageDialog(null, "Perubahan data pegawai berhasil disimpan");
                this.jPaneEditPeg.setVisible(false);
                enablein();
            }
            
            else
            {
                
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.jPaneEditPeg.setVisible(false);
        enablein();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected())
        {
            jRadioButton2.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected())
        {
            jRadioButton1.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton4.isSelected())
        {
            jRadioButton3.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton3.isSelected())
        {
            jRadioButton4.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
            int selectedOption = JOptionPane.showConfirmDialog(null, 
                                  "Apakah Anda yakin ingin menambah pegawai?", 
                                  "Peringatan", 
                                  JOptionPane.YES_NO_OPTION); 
            if (selectedOption == JOptionPane.YES_OPTION) 
            {
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                this.jPaneRegisterMgr.setVisible(false);
                enablein();
            }
            
            else
            {
                
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
                this.jPaneRegisterMgr.setVisible(false);
                enablein();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton5.isSelected())
        {
            jRadioButton6.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton6.isSelected())
        {
            jRadioButton5.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null, 
                                  "Apakah Anda yakin ingin mengedit Manager?", 
                                  "Peringatan", 
                                  JOptionPane.YES_NO_OPTION); 
            if (selectedOption == JOptionPane.YES_OPTION) 
            {
                JOptionPane.showMessageDialog(null, "Perubahan data pegawai berhasil disimpan");
                this.jPaneEditMgr.setVisible(false);
                enablein();
            }
            
            else
            {
                
            }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        this.jPaneEditMgr.setVisible(false);
        enablein();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton9.isSelected())
        {
            jRadioButton10.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton10.isSelected())
        {
            jRadioButton9.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPegawaixManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPegawaixManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPegawaixManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPegawaixManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPegawaixManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox32;
    private javax.swing.JComboBox jComboBox33;
    private javax.swing.JComboBox jComboBox34;
    private javax.swing.JComboBox jComboBox35;
    private javax.swing.JComboBox jComboBox36;
    private javax.swing.JComboBox jComboBox37;
    private javax.swing.JComboBox jComboBox38;
    private javax.swing.JComboBox jComboBox39;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox40;
    private javax.swing.JComboBox jComboBox41;
    private javax.swing.JComboBox jComboBox42;
    private javax.swing.JComboBox jComboBox43;
    private javax.swing.JComboBox jComboBox44;
    private javax.swing.JComboBox jComboBox45;
    private javax.swing.JComboBox jComboBox46;
    private javax.swing.JComboBox jComboBox47;
    private javax.swing.JComboBox jComboBox48;
    private javax.swing.JComboBox jComboBox49;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox50;
    private javax.swing.JComboBox jComboBox51;
    private javax.swing.JComboBox jComboBox52;
    private javax.swing.JComboBox jComboBox53;
    private javax.swing.JComboBox jComboBox54;
    private javax.swing.JComboBox jComboBox55;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPaneEdit1;
    private javax.swing.JPanel jPaneEdit3;
    private javax.swing.JPanel jPaneEditMgr;
    private javax.swing.JPanel jPaneEditPeg;
    private javax.swing.JPanel jPaneRegisterMgr;
    private javax.swing.JPanel jPaneRegisterPeg;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
