/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.controller;

/**
 *
 * @author Aldi
 */
public class tesDebugging extends javax.swing.JFrame {
    private controller con = new controller();
    /**
     * Creates new form tesDebugging
     */
    public tesDebugging() {
        initComponents();
        con.getAll();
        jTextArea1.setText(getKategoriBarang());
    }

    public String getManager(){
        int i;
        String temp="";
        for(i=0;i<con.getDummyManager().size();i++)
        {
            temp+=con.getDummyManager().get(i).tampil();
        }
        return temp;
    }
    
    public String getStaff(){
        int i;
        String temp="";
        for(i=0;i<con.getDummyStaff().size();i++)
        {
            temp+=con.getDummyStaff().get(i).tampil();
        }
        return temp;
    }
    
    public String getAllPegawai(){
        return getManager()+getStaff();
    }
    
    public String getBarang(){
        int i;
        String temp="";
        for(i=0;i<con.getDummyBarang().size();i++)
        {
            temp+=con.getDummyBarang().get(i).tampil();
        }
        return temp;
    }
    
    public String getMember(){
        int i;
        String temp="";
        for(i=0;i<con.getdummyMember().size();i++)
        {
            temp+=con.getdummyMember().get(i).tampil();
        }
        return temp;
    }
    
    public String getKategoriBarang(){
        int i;
        String temp="";
        for(i=0;i<con.getdummyKetegoriBarang().size();i++)
        {
            temp+=con.getdummyKetegoriBarang().get(i).tampil();
        }
        return temp;
    }
     
    public String getRole(){
        int i;
        String temp="";
        for(i=0;i<con.getdummyRole().size();i++)
        {
            temp+=con.getdummyRole().get(i).tampil();
        }
        return temp;
    }
    
    public String getSupplier(){
        int i;
        String temp="";
        for(i=0;i<con.getdummySupplier().size();i++)
        {
            temp+=con.getdummySupplier().get(i).tampil();
        }
        return temp;
    }
    
    public String getUsers(){
        int i;
        String temp="";
        for(i=0;i<con.getdummyUsers().size();i++)
        {
            temp+=con.getdummyUsers().get(i).tampil();
        }
        return temp;
    }
    
    public String getTransaksi(){
        int i;
        String temp="";
        for(i=0;i<con.getdummyUsers().size();i++)
        {
            temp+=con.getdummyUsers().get(i).tampil();
        }
        return temp;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tesDebugging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tesDebugging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tesDebugging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tesDebugging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tesDebugging().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
